version: '3.3'
services:
    mysql8-master:
        image: mysql:8.0.26
        container_name: mysql8-master
        volumes: 
          - ./config/master.cnf:/etc/mysql/my.cnf
          - ./config/master.cnf:/etc/mysql/mysql.conf.d/my.cnf
          - ${MASTER_DATA}:/var/lib/mysql
        ports:
          - 3380:3306
        environment:
          - "MYSQL_ROOT_PASSWORD=${MASTER_PASSWD}"
        
    mysql8-slave:
        image: mysql:8.0.26
        container_name: mysql8-slave
        depends_on:
          - mysql8-master
        volumes: 
          - ./config/slave.cnf:/etc/mysql/my.cnf
          - ./config/slave.cnf:/etc/mysql/mysql.conf.d/my.cnf
          - ${SLAVE_DATA}:/var/lib/mysql
        ports:
          - 3381:3306
        environment:                           
          - "MYSQL_ROOT_PASSWORD=${SLAVE_PASSWD}"
